openapi: 3.0.1
info:
  title: MSAG Conversion Service
  version: "1.0"
servers:
  - url: http://localhost/Mcs/v1
paths:
  /PidfloToMsag:
    post:
      tags:
        - PIDFLOtoMSAGConversion
      summary: Converts PIDF-LO to MSAG data
      operationId: PIDFLOtoMSAGConversion
      requestBody:
        description: PIDF-LO data
        content:
          application/json:
            schema:
              type: string
        required: true
      responses:
        '200':
          description: Data successfully converted
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/MsagData'
        '307':
          description: Temporary Redirect
          headers:
            Location:
              description: Referral URI of another MCS
              schema:
                type: string
                format: uri
        '454':
          description: Unspecified Error
        '468':
          description: No Address Found
        '469':
          description: Unknown MCS/GCS
  /MsagToPidfLo:
    post:
      tags:
        - MSAGtoPIDFLOConversion
      summary: Converts MSAG to PIDF-LO data
      operationId: MSAGtoPIDFLOConversion
      requestBody:
        description: MSAG data
        content:
          application/json:
            schema:
              type: string
        required: true
      responses:
        '200':
          description: Data successfully converted
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/PidfLoData'
        '307':
          description: Temporary Redirect
          headers:
            Location:
              description: Referral URI of another MCS
              schema:
                type: string
                format: uri
        '454':
          description: Unspecified Error
        '468':
          description: No Address Found
        '469':
          description: Unknown MCS/GCS
  /Versions:
    servers:
      - url: https://api.example.com/Mcs
        description: Override base path for Versions query
    get:
      tags:
        - RetrieveVersions
      summary: Retrieves all supported versions, vendor parameter is optional.
      operationId: RetrieveVersions
      responses:
        '200':
          description: Versions found
          content:
            application/json:
              schema:
                $ref: 'i3-common.yaml#/components/schemas/VersionsArray'
components:
  schemas:
    PidfLoData:
      type: object
      required:
        - pidfLoAddress
      properties:
        pidfLoAddress:
          type: string
    MsagData:
      type: object
      required:
        - msagAddress
      properties:
        msagAddress:
          type: string